### ISSUE TITLE
Improved Signup Flow

### ISSUE THREAD

**Issue by byndcivilization** [advisorconnect/advisorconnect-roadmap#37]
## Detailed Description
- increase auth/link acct options
- improve flow from sign in to Network Analysis

## Context
Users need an improved signup flow. This includes:
- More options for authentication
- More chances to resolve a user to a prospect record and add to the user._details field

## Implementation Issues
- [x] New link accounts screen (waiting for mocks to create ticket)
   - [x] ui - https://github.com/advisorconnect/ui/issues/552
- [x] [improve LinkedIn upload](https://github.com/advisorconnect/advisorconnect-roadmap/issues/36)
- [x] [improve Gmail connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/38)
- [x] [improve Yahoo connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/6)
- [ ] [improve Microsoft connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/4)
- [ ] [improve AOL connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/39)
- [ ] [Implement iCloud connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/41)
- [ ] [Implement Twitter connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/5)
- [x] [Implement Facebook connect accts](https://github.com/advisorconnect/advisorconnect-roadmap/issues/40)
