### ISSUE TITLE
AOL auth0 connect accounts and pull

### ISSUE THREAD

**Issue by byndcivilization** [advisorconnect/advisorconnect-roadmap#39]
## Detailed Description
- let a user connect aol account via auth0
- feed connected account profile into resolution and write on user._details
- automatically pull aol contacts when we connect accounts

## Context
This will give us another touchpoint to identify a user to feed into things like commonalities and recommendations and automatically grab contacts

## Possible Implementation
- [ ] ui
  - [ ] reimplement auth0 connection - https://github.com/advisorconnect/ui/issues/554
  - [ ] successful account link hits link accounts route - https://github.com/advisorconnect/ui/issues/557
---
- [ ] ui-api
  - [ ] update user model to bundle connect account flags - https://github.com/advisorconnect/ui-api/issues/30
  - [ ] link accounts route for aol - https://github.com/advisorconnect/ui-api/issues/29
---
- [ ] svc-sync
  - [ ] pull aol contacts and initiate aol ingestion - https://github.com/advisorconnect/service-sync/issues/23
---
- [ ] svc-ingest-initiation
  - [ ] create listener to kick off ingestion for aol - https://github.com/advisorconnect/service-ingest-initiation/issues/7
---
- [ ] svc-ingestion
  - [ ] ingest aol batches - https://github.com/advisorconnect/service-ingestion/issues/91
---
- [ ] svc-data-adapter
   - [ ] create direct aol data adapter - https://github.com/advisorconnect/service-data-adapter/issues/70
---   
- [ ] feed profile into resolution and write to  user db
- [ ] send ingestion pull to sync
- [ ] sync will pull contacts via manager api token exchange
- [ ] data adapter module for sources 
- [ ] ingestion routes

**Comment by byndcivilization** [comment]
currently holding in cloud sponge
