### ISSUE TITLE
Microsoft auth0 connect accounts and pull

### ISSUE THREAD

**Issue by byndcivilization** [advisorconnect/advisorconnect-roadmap#4]
## Detailed Description
- let a user connect microsoft account via auth0
- feed connected account profile into resolution and write on user._details
- automatically pull microsoft contacts when we connect accounts

## Context
This will give us another touchpoint to identify a user to feed into things like commonalities and recommendations and automatically grab contacts

## Possible Implementation
- [ ] ui
  - [ ] reimplement auth0 connection - https://github.com/advisorconnect/ui/issues/554
  - [ ] successful account link hits link accounts route - https://github.com/advisorconnect/ui/issues/557
---
- [ ] ui-api
  - [ ] update user model to bundle connect account flags - https://github.com/advisorconnect/ui-api/issues/30
  - [ ] link accounts route for microsoft - https://github.com/advisorconnect/ui-api/issues/29
---
- [ ] svc-sync
  - [ ] pull microsoft contacts and initiate microsoft ingestion - https://github.com/advisorconnect/service-sync/issues/24
---
- [ ] svc-ingest-initiation
  - [ ] create listener to kick off ingestion for microsoft - https://github.com/advisorconnect/service-ingest-initiation/issues/8
---
- [ ] svc-ingestion
  - [ ] ingest microsoft batches - https://github.com/advisorconnect/service-ingestion/issues/92
---
- [ ] svc-data-adapter
   - [ ] create direct microsoft data adapter - https://github.com/advisorconnect/service-data-adapter/issues/69

**Comment by byndcivilization** [comment]
currently holding with cloud sponge
